In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4]);

In [4]:
arr+1 #scaler addition , 1 id added to every element

array([2, 3, 4, 5])

In [5]:
arr**2 

array([ 1,  4,  9, 16])

In [6]:
#matrix multiplaction

In [7]:
arr=np.diag([1,2,3,4])

In [11]:
arr 

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [9]:
arr*arr #dot 

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [12]:
arr.dot(arr) #dot

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

### compresion element wise

In [14]:
a=np.array([1,2,3,4,5])
b=np.array([1,4,3,4,6])

In [16]:
a==b # element wise compression

array([ True, False,  True,  True, False])

In [19]:
a<b #element wise

array([False,  True, False, False,  True])

### array-wise comparision

In [20]:
a=np.array([1,2,3,4,5]);
b=np.array([2,3,45,57,4])
c=np.array([1,2,3,4,5])

In [21]:
np.array_equal(a,b)

False

In [22]:
np.array_equal(a,c)

True

In [37]:
a=np.arange(1,9)

In [38]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154])

In [40]:
np.sin(90)

0.8939966636005579

#### reduce

In [42]:
x=np.array([1,2,3,4,5])

In [54]:

arr=np.array([[23,65],[1,3]])

In [55]:
arr.sum(axis=0) #from top to bootam

array([24, 68])

In [56]:
arr.sum(axis=1)

array([88,  4])

In [58]:
data=np.loadtxt("./pop.txt")

In [59]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [64]:
year,heres,lynxes,carrots=data.T #data.T transpose

In [63]:
year

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [65]:
#mean population time 

In [68]:
pop=data[:,1:] #[rows,colums] --> #[select all rows,but colimns from 1:last i.e exclude the oth index which is year ]

In [69]:
pop

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [71]:
pop.std(axis=0) #standred devation for the population of all the three animals

array([20897.90645809, 16254.59153691,  3322.50622558])

In [74]:
np.max(pop,axis=1) ## higest population every year 

array([48300., 48200., 70200., 77400., 59400., 41700., 38600., 42300.,
       44500., 42100., 46000., 46800., 57000., 76600., 52300., 51100.,
       36700., 41800., 43300., 41300., 47300.])

In [75]:
np.argmax(pop,axis=1) ## higest population every year indexxx


array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])